### PR TITLE
Clojure translation part II

### LINKED ISSUE #518: 1.14.0 - Rule parse error in rule clojure.lang.security.documentbuilderfactory-xxe.documentbuilderfactory-xxe
**Describe the bug**

running a scan with version 1.14.0 results in:
```
[ERROR] Rule parse error in rule clojure.lang.security.documentbuilderfactory-xxe.documentbuilderfactory-xxe:
 Invalid pattern for Clojure: Failure: Invalid defn form.
----- pattern -----
(defn ... ... ( ... ))

----- end pattern -----
```

**To Reproduce**

```bash
wget https://github.com/opengrep/opengrep/releases/download/v1.14.0/opengrep_manylinux_x86
chmod +x opengrep_manylinux_x86
mkdir target
touch target/test
./opengrep_manylinux_x86 scan target

┌──────────────┐
│ Opengrep CLI │
└──────────────┘

                                                                                                                        
Scanning 1 file (only git-tracked) with:
                                      
✔ Semgrep OSS
  ✔ Basic security coverage for first-party code vulnerabilities.
                                                    
✨ Learn more at https://opengrep.dev.
                                                    
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00                                                                                                                        
[ERROR] Rule parse error in rule clojure.lang.security.documentbuilderfactory-xxe.documentbuilderfactory-xxe:
 Invalid pattern for Clojure: Failure: Invalid defn form.
----- pattern -----
(defn ... ... ( ... ))

----- end pattern -----

                
                
┌──────────────┐
│ Scan Summary │
└──────────────┘
Some files were skipped or only partially analyzed.
  Partially scanned: 1 files only partially analyzed due to parsing or internal Opengrep errors

Ran 48 rules on 1 file: 0 findings.
⚡ Contribute to Opengrep at https://github.com/opengrep/opengrep.
```

**Expected behavior**

the scan completes without errors - as it does with previous versions including 1.13.2.

**Screenshots**
 
n/a

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Opengrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
* localhost with manual download of official binary from github releases page
* same result on ci environment with an `install.sh` installation 

**Use case**

the error prevents our ci pipeline from completing successfully, i.e. the opengrep scan jobs always fail.

### PR DESCRIPTION
**Pull request by dimitris-m**
## Changes 

- Removes synthetic variables from the intermediate variables, since the tokens used are real tokens with different content in the target file. This improves dataflow traces in text / json / sarif.
- Improves printing of matches which in some cases failed with macroexpanded code.
- Encodes the special ops as is done in other languages.
- Adds loop and recur (this can be used with loop or functions, in tail position). Note: I did not add a test for defn + recur because it made me realise we have other issues that are related and need to be fixed, and these are orthogonal to the translation.
- Improves patterns: 
  - `(...)` matches a block and not a `Call(..., [])`;
  - `...`, when function parameters are expected, becomes `[...]`;
  - `...`, when a single name is expected, becomes `$_`.
- Fixes #518.
- Removes the IL macroexpansion mechanics; this approach ended up being too problematic compared to macroexpansion at AST generic translation time.

- Adds comments and TODOs: some will be dealt with in this PR.

- There will be Part III.

### CODE REVIEW

File: languages/lisp/tree-sitter/Macro_expand_clojure.ml [hunk 1]
```diff
@@ -1,298 +1,37 @@
...
+   | "->" | "->>" | "cond->" | "cond->>"
     -> true
   | _
     -> false
 
 (* XXX: It would be more robust to match on macroexpansion_mode as above. *)
 let is_macroexpandable (todo_kind : string) =
   match todo_kind with
-  | "->" | "->>" | "cond->" | "cond->>" | "as->" | "ShortLambda"
+  | "as->" | "ShortLambda"
```
Comment (corneliuhoffman) [inline languages/lisp/tree-sitter/Macro_expand_clojure.ml:25]: wait so the -> liek things are no longer macroexpandable?

Comment (dimitris-m) [reply languages/lisp/tree-sitter/Macro_expand_clojure.ml:25]: They are, but at translation to generic.
There were 2 methods: during IL translation and during to-generic.

Now what is kept is to-generic. That means we shuffle CST stuff not generic AST.

Comment (dimitris-m) [reply languages/lisp/tree-sitter/Macro_expand_clojure.ml:25]: Until before this commit I had both methods there, hoping to resurrect the IL method but I decided to abandon it.

File: languages/lisp/tree-sitter/Parse_clojure_tree_sitter.ml [hunk 2]
```diff
@@ -257,6 +250,7 @@ let radix_regex =
 
 let qualified_name_regex_str = "^\\(.+\\)/\\(.+\\)$"
 
+let fake_variable_ident = "G__1111"
```
Comment (corneliuhoffman) [inline languages/lisp/tree-sitter/Parse_clojure_tree_sitter.ml:253]: oh common, call it G_666

**Review by corneliuhoffman — APPROVED** [review]
I really liked the details in the recur/loop stuff ... this is better and better, soon will be a flag language for us
