### PR TITLE
Fix #291: cwd can begin with lowecase drive letter on windows

### LINKED ISSUE #291: Opengrep fails to scan on Windows due to case sensitivity in path comparison
**Describe the bug**

Scan fails on Windows due to case sensitivity issues in path comparison. The scanner cannot generate relative paths when the current working directory and project root have different case in the drive letter (e.g., `c:\` vs `C:\`), causing the scan to fail with the error "cannot make path '.' relative to project root".

**To Reproduce**

1. Run Opengrep on a Windows system where the current working directory is returned with a lowercase drive letter (e.g., `c:\Users\User\Downloads\proj`)
2. The project root is detected with an uppercase drive letter (e.g., `C:\Users\User\Downloads\proj`)
3. Execute any scan command, for example:
   ```
   opengrep-cli scan --json --experimental --disable-version-check --config <config-path>
   ```

**Expected behavior**
The scan should proceed normally, recognizing that paths with different case are equivalent on Windows file systems (which are case-insensitive by default).

**Screenshots**
Error message:

```
[01.81][ERROR]: Error: cannot make path "." relative to project root "C:\\Users\\User\\Downloads\\proj".
cwd: c:\Users\User\Downloads\proj
realpath for .: { Rfpath.fpath = .;
rpath = (Rpath.Rpath C:\Users\User\Downloads\proj);
cwd = (Rpath.Rpath C:\Users\User\Downloads\proj) }
```

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Opengrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Windows system running official Opengrep binary

**Use case**
Fixing this bug will enable Windows users to run Opengrep scans without encountering path resolution failures due to case sensitivity mismatches. This is essential for Windows adoption since the current behavior makes Opengrep unusable on Windows systems where different system calls return paths with inconsistent case.

**Technical Details**
The issue occurs in the `Ppath.ml` module where path comparison functions (`Fpath.equal`, `Fpath.rem_prefix`) perform case-sensitive string comparisons even on Windows where file systems are case-insensitive. The bug manifests when:

- `Unix.getcwd()` returns a path with one case (e.g., uppercase drive letter)
- `Sys.getcwd()` returns the same path with different case (e.g., lowercase drive letter)
- Path prefix removal fails because `"C:\path"` ≠ `"c:\path"` in string comparison

**Proposed Solution**
Implement case-insensitive path comparison on Windows by:
1. Adding Windows-specific path normalization functions
2. Using case-insensitive comparison in `remove_prefix` and `relativize` functions
3. Adding case-insensitive regex compilation for glob patterns on Windows
4. Ensuring consistent use of `Unix.getcwd()` vs `Sys.getcwd()`

### PR DESCRIPTION
**Pull request by dimitris-m**
Closes #291.

Plus small changes in other places, as noted in commits.

### CODE REVIEW

File: libs/paths/Ppath.ml [hunk 1]
```diff
@@ -287,12 +287,27 @@ let remove_prefix root path =
 (* Builder entry points *)
 (*****************************************************************************)
 
+let capitalize_drive_letter path =
+  if String.length path >= 2 &&
+     Char.equal path.[1] ':' &&
+     path.[0] >= 'a' && path.[0] <= 'z'
+  then
+    let upper = Char.uppercase_ascii path.[0] in
```
Comment (corneliuhoffman) [inline libs/paths/Ppath.ml]: can one not use String.capitalize_ascii?

Comment (dimitris-m) [reply libs/paths/Ppath.ml]: I left a comment on the commit message: since some windows filesystems like NTFS can be case sensitive, I did not want to change the whole path.

**Comment by dimitris-m** [comment]
> This looks good to me, I don't have a  window machine to test though

I tested with a python script on windows, maybe I can paste it on the PR description.

File: libs/paths/Ppath.ml (hunk 1 above)
Comment (corneliuhoffman) [reply libs/paths/Ppath.ml]: yes but String.capitalize_ascii just capitalizes the first char. I think that is equivalent to your hack

Comment (dimitris-m) [reply libs/paths/Ppath.ml]: oh, ok yes

Comment (dimitris-m) [reply libs/paths/Ppath.ml]: fixed
