### PR TITLE
Modernise C#

### LINKED ISSUE #460: C#: Support primary constructors syntax
Code like the following fails to parse the part `(EntityDbContext dbContext)`:

``` csharp
public class Person(EntityDbContext dbContext) : IPerson
{
    public void SayHello()
    {
        Console.WriteLine($"Hello! Connected to database: {dbContext.ConnectionString}");
    }
}

public class Program
{
    public static void Main()
    {
        var dbContext = new EntityDbContext();
        IPerson person = new Person(dbContext);
        person.SayHello();
    }
}
```

### PR DESCRIPTION
**Pull request by maciejpirog**
This PR adds support for some missing constructions from the more recent versions of C# (12, 13, and 14). This PR includes the most important syntactic additions, but there are still some TODOs.

- [Primary constructors](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-12#primary-constructors) (closes #460)
- [`ref readonly` parameters](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-12#ref-readonly-parameters)
- [`using` can alias any type](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-12#alias-any-type)
- [`params collections`](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-13#params-collections)
- [conditional assignment](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-14#null-conditional-assignment)

### CODE REVIEW

**Comment by dimitris-m** [comment]
I recommend to open PR in semgrep-c-sharp too, targeting opengrep/main.

File: languages/csharp/generic/Parse_csharp_tree_sitter.ml [hunk 1]
```diff
@@ -2386,7 +2386,7 @@ and parameter (env : env) (v1 : CST.parameter) : G.parameter =
   | `Ellips v1 -> ParamEllipsis (token env v1)
 
 and parameter_type_with_modifiers (env : env)
-    ((v1, v2, v3, v4) : CST.parameter_type_with_modifiers) =
+    ((v1, v2, v3, _readonly, v4) : CST.parameter_type_with_modifiers) =
```
Comment (dimitris-m) [inline languages/csharp/generic/Parse_csharp_tree_sitter.ml:2390]: Add as attribute as discussed offline

Comment (maciejpirog) [reply languages/csharp/generic/Parse_csharp_tree_sitter.ml:2390]: will add in a subsequent PR
