### PR TITLE
Tainting: per-arity signature extraction for Clojure and Elixir

### LINKED ISSUE #561: Improved clojure HOFs parsing
Tried the clojure version of the HOFs test and failed. Attaching an automatically generated version of the test (added txt bc github)

[test_hof_comprehensive_clojure.yaml](https://github.com/user-attachments/files/25016097/test_hof_comprehensive_clojure.yaml)

[test_hof_comprehensive_clojure.clj.txt](https://github.com/user-attachments/files/25016088/test_hof_comprehensive_clojure.clj.txt)

### PR DESCRIPTION
**Pull request by dimitris-m**
## Summary

- Extract **N separate taint signatures** (one per arity branch) for Clojure multi-arity functions and Elixir multi-clause lambdas, instead of a single merged signature with `params = [PRest !!_implicit_param!]`
- Add `sig_arity` type (`Arity_exact | Arity_at_least`) for rest-param support, with fallback lookup semantics
- Add built-in HOF configs for Clojure (`map`, `filter`, `keep`, `reduce`, `mapcat`, etc.)
- Unwrap Clojure CList arguments so individual args are visible to taint analysis
- Enable **implicit return** for Clojure (`lang_supports_implicit_return`), enabling cross-function return-value taint propagation (e.g. `(defn get-data [x] (source))` now produces a `ToReturn` effect)
- Bridge the `OtherExpr("ExprBlock", ...)` wrapper gap in `AST_to_IL.stmt_aux`: Clojure's AST wraps function bodies in `ExprBlock`, so `mark_first_instr_ancestor` sets `is_implicit_return` on the inner expression but `stmt_aux` checked the outer wrapper. Now propagates through by checking the last expression in the block.
- Remove redundant `detect_user_hof` from call graph construction: `all_callback_args` already identifies every function reference passed as an argument, making the `user_hofs` path purely duplicative (confirmed by DOT graph comparison and full test suite)

Closes #561

## Checks

- [x] `test_hof_comprehensive_clojure`: custom HOF with named callback, inline lambda, multi-arity delegation, built-in `map`/`filter`/`reduce`/`keep`/`mapcat`/etc.
- [x] `test_hof_comprehensive_clojure`: cross-function return taint via implicit return (`get-history`/`mapcat`/`process-history` from issue #561)
- [x] `test_hof_comprehensive_clojure`: variadic arity (`& rest`) delegation and rest-param sink
- [x] `test_hof_multi_clause_elixir`: multi-clause `fn` lambda as HOF callback, guarded clauses (`PatWhen`)
- [x] All 72 `cross_function_tainting` tests pass after `detect_user_hof` removal

## TODO: Destructuring

Currently HOFs are not identified when they are inside destructuring patterns, we need more work for this and I left it for a future PR.

### CODE REVIEW

File: src/engine/Match_tainting_mode.ml [hunk 1]
```diff
@@ -534,48 +534,199 @@ let check_rule per_file_formula_cache (rule : R.taint_rule) match_hook
...
-              let _flow, fdef_effects, _mapping =
-                check_fundef taint_inst info.name !ctx ~glob_env
-                  ?class_name:info.class_name_str ~signature_db:updated_db
-                  ?builtin_signature_db ?call_graph:(Some relevant_graph)
-                  info.fdef
-              in
-              record_matches fdef_effects;
-              updated_db
+              match fdef.G.fbody with
+              | G.FBStmt { G.s = G.Switch (_, _, cases); _ } ->
```
Comment (maciejpirog) [inline src/engine/Match_tainting_mode.ml]: Don't we want to check if we switch on the implicit arg, not to confuse with legitimate switch in a function with an implicit arg? Or are implicit args used only to simulate multi-arity functions?

File: src/engine/Match_tainting_mode.ml [hunk 2]
```diff
@@ -534,48 +534,199 @@ let check_rule per_file_formula_cache (rule : R.taint_rule) match_hook
...
-            let params = Tok.unbracket info.fdef.fparams in
-            let arity = get_arity params info lang in
-            let updated_db, _signature =
-              Taint_signature_extractor.extract_signature_with_file_context
-                ~arity ~db ?builtin_signature_db taint_inst ~name:info.name
-                ~method_properties:info.method_properties
-                ~call_graph:(Some relevant_graph) info.cfg ast
+          (* Convert a Case pattern back into a [G.parameter list] for per-arity
+           * signature extraction (Clojure multi-arity / Elixir multi-clause). *)
+          let params_of_case_pattern (pat : G.pattern) : G.parameter list =
```
Comment (maciejpirog) [inline src/engine/Match_tainting_mode.ml]: Would it be much work to extract `params_of_case_pattern` and `process_fun_info` out of `check_rule`? At the moment, `check_rule` has 600 LOC and is totally human-unreadable.

File: src/tainting/Shape_and_sig.ml [hunk 3]
```diff
@@ -765,18 +804,41 @@ let lookup_signature (db : signature_database) (name : Function_id.t) (arity : i
...
-      let total_sigs_card = SignatureSet.cardinal sigs in      
+      let total_sigs_card = SignatureSet.cardinal sigs in
       (* If there's only one signature for this function name, return it regardless of arity *)
       if total_sigs_card =*= 1 then
         Some (SignatureSet.choose sigs).sig_
       else
-        let filtered_sigs =
-          SignatureSet.filter (fun x -> Int.equal arity x.arity) sigs
+        (* Try exact match first *)
+        let exact =
```
Comment (maciejpirog) [inline src/tainting/Shape_and_sig.ml]: Code duplication (vs line 763)

File: src/engine/Match_tainting_mode.ml (hunk 2 above)
Comment (maciejpirog) [reply src/engine/Match_tainting_mode.ml]: Disregard, I'm reading commit-by-commit and it was indeed fixed in the next commit

File: src/engine/Match_tainting_mode.ml (hunk 1 above)
Comment (dimitris-m) [reply src/engine/Match_tainting_mode.ml]: Implicit args are only used to simulate, there is no legitimate function using them and I don't expect this to be an issue because the implicit arg is not a valid clojure identifier.

File: src/engine/Match_tainting_mode.ml (hunk 2 above)
Comment (dimitris-m) [reply src/engine/Match_tainting_mode.ml]: no, I agree, will refactor

File: src/tainting/Shape_and_sig.ml (hunk 3 above)
Comment (maciejpirog) [reply src/tainting/Shape_and_sig.ml]: Disregard. Fixed in the next commit

File: src/engine/Match_tainting_mode.ml (hunk 2 above)
Comment (dimitris-m) [reply src/engine/Match_tainting_mode.ml]: but I did do a refactor step

File: src/engine/Match_tainting_mode.ml (hunk 1 above)
Comment (maciejpirog) [reply src/engine/Match_tainting_mode.ml]: Maybe just in case we should restrict this to Clojure and Elixir? Unless I missed something, this transformation is not guarded by a `Lang`

**Comment by maciejpirog** [comment]
lgtm

File: src/engine/Match_tainting_mode.ml (hunk 1 above)
Comment (dimitris-m) [reply src/engine/Match_tainting_mode.ml]: Good point, will do

Comment (dimitris-m) [reply src/engine/Match_tainting_mode.ml]: I think maybe this is not needed because we may have more such cases, for example OCaml `function`.

File: src/engine/Match_tainting_mode.ml [hunk 4]
```diff
@@ -276,6 +276,102 @@ let get_arity params info lang =
   in
   List.length filtered_params
 
+(** Convert a Case pattern back into a [G.parameter list] for per-arity
+    signature extraction (Clojure multi-arity / Elixir multi-clause). *)
```
Comment (corneliuhoffman) [inline src/engine/Match_tainting_mode.ml:280]: should we guard for clojure/elixir nly ... not knowledgable enough to see if this can happen "by mistake" in other langs?

File: src/tainting/Shape_and_sig.ml [hunk 5]
```diff
@@ -644,7 +644,13 @@ end = struct
   let of_IL_params il_params =
     il_params
     |> List_.map (function
-         | IL.Param { pname = { ident = s, _; _ }; _ } -> P s
+         | IL.Param { pname = { ident = s, _; _ }; _ } ->
```
Comment (corneliuhoffman) [inline src/tainting/Shape_and_sig.ml]: is this not a job of AST_to_IL? looks wrong to me that that is a Param?

File: src/engine/Match_tainting_mode.ml (hunk 4 above)
Comment (dimitris-m) [reply src/engine/Match_tainting_mode.ml:280]: The encoding is detected quite precisely, in fact OCaml's `function` also uses it -- not sure it is worth to gate this.

Comment (dimitris-m) [reply src/engine/Match_tainting_mode.ml:280]: That is if you look at `extract_multi_arity_cases` where this is used.

**Review by maciejpirog — APPROVED** [review]

File: src/tainting/Shape_and_sig.ml (hunk 5 above)
Comment (dimitris-m) [reply src/tainting/Shape_and_sig.ml]: Maybe it could be PRest yes

Comment (dimitris-m) [reply src/tainting/Shape_and_sig.ml]: ok you are right, I will change

Comment (dimitris-m) [reply src/tainting/Shape_and_sig.ml]: fixed
