### PR TITLE
Php modernisation

### LINKED ISSUE #297: PHP 5->Php 8.4 parser
## **Describe the bug**

 In issue #295 we discovered 2 things
1. the menhir parser (default) is not updated to latest php
2. there is a bug in the tree-sitter parser that interpolates strings wrongly. 

While we should eventually fix the interpolation issue in tree-sitter this does not help since the pattern parsing in php is done via menhir.
In digging in the php updates I found other unparsable syntax:

issues remainig for the parser:
1. [ ] static return type:

```php
function f(): static {}
```
2. [x]  Match expressions:
```php
match($x) {
    1 => 'one',
    2 => 'two',
};
```
3. [x]  Enums:
```php
enum Status {
  case Active;
  case Inactive;
}
```
4. [x]  Null coallescing assignment
```php
$a ??= 'default';
```
5. [x]  Array spread:
```php
$parts = ['apple', 'pear'];
$fruits = ['banana', 'orange', ...$parts, 'watermelon'];
```
and non-numeric
```php
$arr = ["a" => 1, ...$b];
```
6. [ ]  Readonly props or classes
```php
readonly class C { public int $i; }
class C { public readonly int $i; }
```
7. [ ]  Dnf types, standalone types
```php
function f((A&B)|C $x) {}
```
8. [ ]  propery hooks
```php
public string $credits { get { /*...*/ } }
```
9. [ ]  Asymmetric visibility
```php
public private(set) int $i;
```
10. [x]  new without parentheses chaining
```php
new C($a)->meth();
```
11. [ ] [Class constant visibility](https://wiki.php.net/rfc/class_const_visibility), introduced in PHP version 7.1. (thanks @bblumenwiese)

Example:
```php
class C { public const string P = 'Public'; }
class C { protected const string P = 'Protected'; }
class C { private const string P = 'Private'; }
```

### **To Reproduce**
Steps to reproduce the behavior.

This bug is somewhat subtle and so not very obvious to reproduce, there are two possible ways
1. in Parse_target2.ml comment out [this line](https://github.com/opengrep/opengrep/blob/80a6332c484b9e66bfc00d172c986da84f0523fb/src/parsing_languages/Parse_target2.ml#L129), make the project and try to parse any of the above.
2. do not comment the project but create code containing one of the above as well as the following syntax:
```php
function f($filename) {
    "convert $filename";
}
```
then apply the following rule 
```yaml
rules:
- id: embedded_word
  message: "The web server executes a command on potential unescaped user input, which may lead to remote command execution."
  languages:
    - php
  severity: ERROR
  mode: taint
  options:
    taint_assume_safe_numbers: true
  pattern-sinks:
  - patterns:  
    - pattern: $SOURCE
  pattern-sources:
  - patterns:
    - focus-metavariable: $SOURCE
    - pattern-either:
        - pattern: function $FUNC(..., $SOURCE, ...) { ... }
```
If opengrep finds the rule then you are ok. Otherwise you messed up.

### **Expected behavior**
Menhir should parse all the above syntax

### PR DESCRIPTION
**Pull request by corneliuhoffman**
PHP 7.1 - 8.4 Syntax Support

  Adds comprehensive PHP syntax support to the Menhir parser. Closes #297.

  ---
  b0529bca0f - added tests

  Initial test files for PHP 8.x features.

  ---
  d3da6612c4 - readonly fix

  PHP 8.2: Readonly Classes
```php
  readonly class ImmutablePoint {
      public int $x;
      public int $y;
  }
```
  ---
  18aa6ce570 - Union and Intersection DNF

  PHP 8.2: DNF Types (Disjunctive Normal Form)
```php
  function process((Countable&Iterator)|null $input): (A&B)|C {
      // ...
  }
```
  ---
  b59447d2ff - property hooks

  PHP 8.4: Property Hooks
```php
  class User {
      // Block syntax
      public string $name {
          get { return $this->name; }
          set { $this->name = strtoupper($value); }
      }

      // Arrow syntax
      public int $age {
          get => $this->age;
          set => max(0, $value);
      }
  }
```
  ---
  aaed1fb1ad - asymmetric visibility private(set) and protected(set)

  PHP 8.4: Asymmetric Visibility
```php
  class Counter {
      public private(set) int $count = 0;
      public protected(set) string $name = "";
  }
```
  ---
  19e3d19d50 - few others

  PHP 7.1: Class Constant Visibility
```php
  class Config {
      public const PUBLIC_CONST = 1;
      protected const PROTECTED_CONST = 2;
      private const PRIVATE_CONST = 3;
  }
```
  PHP 7.1: Multi-Catch Exception Handling
```php
  try {
      riskyOperation();
  } catch (InvalidArgumentException | TypeError | ValueError $e) {
      handleError($e);
  }
```
  PHP 8.3: Dynamic Class Constant Fetch
```php
  $name = 'VERSION';
  echo Config::{$name};
```
  ---
e09be5428b27 - first-class callable syntax

  PHP 8.1: First-Class Callable Syntax
```php
  $fn = strlen(...);           // → Closure::fromCallable('strlen')
  $fn = $obj->method(...);     // → Closure::fromCallable([$obj, 'method'])
  $fn = Foo::bar(...);         // → Closure::fromCallable([Foo::class, 'bar'])
```  In semgrep patterns, ... retains its ellipsis meaning.

### CODE REVIEW

File: languages/php/ast/ast_php.ml [hunk 1]
```diff
@@ -269,7 +272,11 @@ and hint_type =
   | HintArray of tok
   | HintQuestion of tok * hint_type
   | HintTuple of hint_type list bracket
-  | HintUnion of hint_type list
+  (* first type, then list of (| tok, type) pairs *)
+  | HintUnion of hint_type * (tok * hint_type) list
+  (* PHP 8.1 intersection types, PHP 8.2 DNF types *)
+  (* first type, then list of (& tok, type) pairs, then parens *)
+  | HintIntersection of hint_type * (tok * hint_type) list * unit bracket
```
Comment (dimitris-m) [inline languages/php/ast/ast_php.ml]: What is `unit bracket` here?

Comment (dimitris-m) [reply languages/php/ast/ast_php.ml]: Maybe this is supposed to be: `(hint_type * (tok * hint_type) list * unit) bracket` ?

Comment (dimitris-m) [reply languages/php/ast/ast_php.ml]: And indeed why not have `HitUnion` also be bracketed? It can be fake brackets when missing.

Comment (corneliuhoffman) [reply languages/php/ast/ast_php.ml]: You are right (without the unit). I was just moving the bracket out of the way but there is no needs. changed

Comment (corneliuhoffman) [reply languages/php/ast/ast_php.ml]: I thought about it, the point is that it seems that HintIntersection has mandatory brackets ... will add for thwe others as well

Comment (corneliuhoffman) [reply languages/php/ast/ast_php.ml]: in fact on second thought this is DNF so the brackets on Union never happen https://wiki.php.net/rfc/dnf_types

File: languages/php/menhir/ast_php_build.ml [hunk 2]
```diff
@@ -822,19 +856,40 @@ and class_variables env ?(add_dollar = true) st acc =
...
+  let kind = match fst hook.ph_kind with
+    | PhGet -> A.PhGet (snd hook.ph_kind)
+    | PhSet -> A.PhSet (snd hook.ph_kind)
+  in
+  let params = match hook.ph_params with
+    | None -> []
+    | Some (_, ps, _) -> List_.map (fun p -> A.ParamClassic (parameter env p)) (comma_list_dots ps)
+  in
+  let body = match hook.ph_body with
+    | PHExpr (_, e) -> Some (A.Expr (expr env e, Tok.unsafe_fake_tok ";"))
```
Comment (dimitris-m) [inline languages/php/menhir/ast_php_build.ml]: Is the `;` really there? Else we could use `AST_generic.sc`.

File: tests/parsing/php/php81_first_class_callable.php [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+// Closures and invokables
+$fn11 = $closure(...);
+$fn12 = $invokableObject(...);
+
+// Array callables
+$fn13 = [$obj, 'method'](...);
+$fn14 = [Foo::class, 'method'](...);
+
+// Complex expressions
+$fn15 = self::{$complex . $expression}(...);
```
Comment (dimitris-m) [inline tests/parsing/php/php81_first_class_callable.php:30]: Is this also `Closure::fromCallable` ?

Comment (dimitris-m) [reply tests/parsing/php/php81_first_class_callable.php:30]: Seems so.

File: tests/parsing/php/php8_property_hooks.php [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+// PHP 8.4: Property hooks
+class PropertyHooks {
+    // Block syntax
+    public string $name {
+        get {
+            return $this->name;
+        }
+        set {
+            $this->name = strtoupper($value);
+        }
```
Comment (dimitris-m) [inline tests/parsing/php/php8_property_hooks.php:27]: I recommend to add a tainting test also for this material. Where `$value` is tainted for example.

Comment (dimitris-m) [reply tests/parsing/php/php8_property_hooks.php:27]: In particular I'm wondering how it relates to #516 and #525.

Comment (dimitris-m) [reply tests/parsing/php/php8_property_hooks.php:27]: cc @maciejpirog

File: tests/rules/php_first_class_callable.yaml [hunk 5]
```diff
@@ -0,0 +1,6 @@
+rules:
+- id: first-class-callable
+  message: Detected first-class callable (desugared to Closure::fromCallable)
+  languages: [php]
+  severity: INFO
+  pattern: Closure::fromCallable(...)
```
Comment (dimitris-m) [inline tests/rules/php_first_class_callable.yaml:6]: We should document that this is the only way to match such constructs.

Comment (dimitris-m) [reply tests/rules/php_first_class_callable.yaml:6]: Maybe in Wiki?

File: tests/rules/php_ellipsis_args.php [hunk 6]
```diff
@@ -0,0 +1,23 @@
+<?php
+// Test that ... in patterns matches any arguments
+// This should NOT be confused with PHP 8.1 first-class callables
```
Comment (dimitris-m) [inline tests/rules/php_ellipsis_args.php:3]: Maybe we can add an example of this, with `// ok` ?

File: tests/rules/php_ellipsis_args.php [hunk 7]
```diff
@@ -0,0 +1,23 @@
...
+
+function test() {
+    # ruleid:ellipsis-args
```
Comment (dimitris-m) [inline tests/rules/php_ellipsis_args.php]: This may work but it's not valid PHP comment right? Should it not be `// ruleid: ellipsis-args` ?

Does it parse?

Same for other comments below.

Comment (dimitris-m) [reply tests/rules/php_ellipsis_args.php]: Oh, it seems valid... ok.

Missing space between : and rule name.

**Comment by corneliuhoffman** [comment]
> Property hooks don't produce correct AST. Example from https://www.php.net/manual/en/language.oop5.property-hooks.php
  whoa, thanks

File: languages/php/menhir/ast_php_build.ml (hunk 2 above)
Comment (corneliuhoffman) [reply languages/php/menhir/ast_php_build.ml]: cleaned up to include that in the PHExpr

File: tests/rules/php_first_class_callable.yaml (hunk 5 above)
Comment (corneliuhoffman) [reply tests/rules/php_first_class_callable.yaml:6]: will add a php upgrade in wiki

File: tests/rules/php_ellipsis_args.php (hunk 7 above)
Comment (corneliuhoffman) [reply tests/rules/php_ellipsis_args.php]: modified

File: tests/rules/php_ellipsis_args.php (hunk 6 above)
Comment (corneliuhoffman) [reply tests/rules/php_ellipsis_args.php:3]: added

File: tests/parsing/php/php8_property_hooks.php (hunk 4 above)
Comment (corneliuhoffman) [reply tests/parsing/php/php8_property_hooks.php:27]: added

File: languages/php/generic/php_to_generic.ml [hunk 8]
```diff
@@ -356,6 +360,45 @@ and expr e : G.expr =
...
       let v1 = expr v1 and v2 = bracket (list argument) v2 in
       G.Call (v1, v2) |> G.e
+  (* PHP 8.1: first-class callable - desugar to Closure::fromCallable(...) *)
+  | FirstClassCallable (callable_expr, tok) ->
+      let callable_arg =
+        match callable_expr with
+        (* strlen(...) → Closure::fromCallable('strlen') *)
+        | Id [ name ] ->
+            let str = fst name in
+            G.Arg (G.L (G.String (fb (str, snd name))) |> G.e)
```
Comment (dimitris-m) [inline languages/php/generic/php_to_generic.ml]: So why not just: 

`G.Arg (G.L (G.String (fb name)) |> G.e)`

File: languages/php/generic/php_to_generic.ml [hunk 9]
```diff
@@ -356,6 +360,45 @@ and expr e : G.expr =
...
+        (* $obj->method(...) → Closure::fromCallable([$obj, 'method']) *)
+        | Obj_get (obj, _arrow, Id [ method_name ]) ->
+            let obj_expr = expr obj in
+            let method_str =
+              G.L (G.String (fb (fst method_name, snd method_name))) |> G.e
```
Comment (dimitris-m) [inline languages/php/generic/php_to_generic.ml]: `G.L (G.String (fb method_name)) |> G.e` ?

File: languages/php/generic/php_to_generic.ml [hunk 10]
```diff
@@ -356,6 +360,45 @@ and expr e : G.expr =
...
+            in
+            G.Arg
+              (G.Container (G.Array, fb [ obj_expr; method_str ]) |> G.e)
+        (* Foo::bar(...) → Closure::fromCallable([Foo::class, 'bar']) *)
+        | Class_get (class_ref, _colons, Id [ method_name ]) ->
+            let class_expr = expr class_ref in
+            let method_str =
+              G.L (G.String (fb (fst method_name, snd method_name))) |> G.e
```
Comment (dimitris-m) [inline languages/php/generic/php_to_generic.ml]: `G.L (G.String (fb method_name)) |> G.e` as above?

File: languages/php/generic/php_to_generic.ml (hunk 8 above)
Comment (corneliuhoffman) [reply languages/php/generic/php_to_generic.ml]: :)) fixed

File: languages/php/generic/php_to_generic.ml (hunk 9 above)
Comment (corneliuhoffman) [reply languages/php/generic/php_to_generic.ml]: ditto

File: languages/php/generic/php_to_generic.ml (hunk 10 above)
Comment (corneliuhoffman) [reply languages/php/generic/php_to_generic.ml]: ditto

File: tests/parsing/php/php71_multi_catch.php [hunk 11]
```diff
@@ -0,0 +1,21 @@
...
+
+class Exception1 extends Exception {}
+class Exception2 extends Exception {}
+class Exception3 extends Exception {}
+
+try {
+    throw new Exception1("error");
+} catch (Exception1 | Exception2 $e) {
+    echo "Caught exception 1 or 2: " . $e->getMessage();
+} catch (Exception3 | \RuntimeException $e) {
```
Comment (dimitris-m) [inline tests/parsing/php/php71_multi_catch.php:12]: Is `\RuntimeException` special (what is the slash)?

Comment (corneliuhoffman) [reply tests/parsing/php/php71_multi_catch.php:12]: I think "\" means "global". The others are in the local file.

File: tests/parsing/php/php8_readonly.php [hunk 12]
```diff
@@ -0,0 +1,14 @@
+<?php
+// PHP 8.1: Readonly properties - WORKS
```
Comment (dimitris-m) [inline tests/parsing/php/php8_readonly.php]: Remove "- WORKS"

File: tests/parsing/php/php8_static_return.php [hunk 13]
```diff
@@ -0,0 +1,7 @@
+<?php
+// PHP 8.0: Static return type - WORKS
```
Comment (dimitris-m) [inline tests/parsing/php/php8_static_return.php]: Remove "- WORKS"

File: tests/parsing/php/php8_readonly.php [hunk 14]
```diff
@@ -0,0 +1,14 @@
...
+class ReadonlyProperty {
+    public readonly int $id;
+
+    public function __construct(int $id) {
+        $this->id = $id;
+    }
+}
+
+// PHP 8.2: Readonly classes - WORKS
```
Comment (dimitris-m) [inline tests/parsing/php/php8_readonly.php]: Remove "- WORKS"

**Review by dimitris-m — APPROVED** [review]
LGTM - modulo small comments
